### ISSUE TITLE
WebpackError required for vite unplugin

### ISSUE THREAD

**Issue by djodjonx** [clawject/clawject#11]
### Current behaviour

An error occur "Cannot find module 'webpack/lib/WebpackError'" when launching project with vite and the clawject unplugin. 

We don't want install webpack for Vite project.

### Minimal reproducible example

https://codesandbox.io/p/devbox/jy7nn9

### Steps to reproduce

- Create a new Vite project
- Add the clawject unplugin vite
- Run build

### Expected behaviour

Project should run without Webpack dependency.

**Comment by artem1458** [comment]
@djodjonx Thanks for the bug report, I will address this issue ASAP

**Comment by artem1458** [comment]
@djodjonx Issue is fixed, you can now bump clawject to ^1.2.2

https://codesandbox.io/p/devbox/clawject-nuxt-forked-r67w39

**Comment by djodjonx** [comment]
@artem1458 thx for the reactivity.
